name: snowfall_or_anythings
description: "A Flutter package to create snowfall or any kind of falling widgets animations."
version: 0.0.6
homepage: https://github.com/ValdirGiorgi/snowfall_or_anythings
repository: https://github.com/ValdirGiorgi/snowfall_or_anythings

screenshots:
  - description: The snowfall animation with default settings.
    path: assets/logos/snowfall_or_anythings.png

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - snowfall
  - animation
  - snow
  - effects
  - christmas
